name: HttpCLient test run
on: 
 workflow_dispatch:

jobs:
  deploy-and-test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Pull API Docker image
        run: docker pull coherentsolutions/rest-training:2.0
      
      - name: Run API Docker container
        run: docker run -d -p 8082:8082 coherentsolutions/rest-training:2.0      
      
      - name: Setup .Net SDK
        uses: actions/setup-dotnet@v4
      
      - name: Get repository code
        uses: actions/checkout@v4
        
      - name: Restore NuGet packages
        run: dotnet restore ApiTestingSolution/ApiTestingSolution.sln
      
      - name: Build ApiTestingSolution
        run: dotnet build ApiTestingSolution/ApiTestingSolution.sln --configuration Release
      
      - name: Run tests
        run: dotnet test ApiTestingSolution/ApiTestingSolution.sln --logger "trx"
              
      - name: List test results directory
        run: ls -R ./allure-results
      
      - name: Publish Allure results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: './allure-results/*.trx'
      
      - name: Install Allure
        if: always()
        run: npm install -g allure-commandline --save-dev

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
        
      - name: Generate Allure report
        if: always()
        run: allure generate ./allure-results --clean -o ./allure-report
      
      - name: List generated Allure report directory
        run: ls -R ./allure-report

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report

      - name: Provide link to the Allure report
        if: always()
        run: echo "## 📊 [Allure report available here](https://${{ github.repository_owner }}.github.io/REST_API_Testing_Training/)" >> $GITHUB_STEP_SUMMARY
