name: API testing
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Pull docker container (coherentsolutions/rest-training:2.0)
        run: docker pull coherentsolutions/rest-training:2.0
      - name: Run docker container (coherentsolutions/rest-training:2.0) on port 8082:8082
        run: docker run -d -p 8082:8082 coherentsolutions/rest-training:2.0      
      - name: Setup .Net SDK
        uses: actions/setup-dotnet@v4
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Restore NuGet packages
        run: dotnet restore --locked-mode
      - name: Build ApiTestingSolution
        run: dotnet build ApiTestingSolution.sln --configuration Release
      - name: Publish test results (optional)
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: TestResults
      - name: Publish Allure report (optional)
        uses: allure-report/upload@v1
        with:
          results: ./TestResults
